# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
o = np.zeros(10)
print(o)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
x = np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
print(x.shape)

(40,)


5. Print the type of the previous array in question 3

In [5]:
print(type(x))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [7]:
print(x.ndim)

1


8. Create a boolean array with all the True values

In [8]:
bool_arr = np.array([1,2,3,4,5,6], dtype=bool)
print(bool_arr)

[ True  True  True  True  True  True]


9. Create a two dimensional array




In [9]:
two_dim = np.array([[1,2,3],[4,5,6]])
print(two_dim)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array



In [10]:
three_dim = np.array([[[1,2,4],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_dim)

[[[ 1  2  4]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
vec = np.array([10,20,30,40,50])
print(vec[::-1])

[50 40 30 20 10]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
null_vec = np.zeros(10)
null_vec[4] = 1
print(null_vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
mat = np.array([[1,1,1],[0,0,0,],[1,1,1]])
print(mat)

[[1 1 1]
 [0 0 0]
 [1 1 1]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1, 2, 3, 4, 5]) 
arr = arr.astype('float64') 
print(arr) 
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],
            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], 
            [7., 2., 12.]])
comparison = arr1 == arr2
equal_arrays = comparison.all() 
print(equal_arrays) 

False


17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr=np.arange(0,10,3)
arr

array([0, 3, 6, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
-a[a % 2 == 1]

array([-1, -3, -5, -7, -9])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
n=np.arange(0,15)
n[5]=12
n[6]=12
n[7]=12
n[8]=12
n

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9, 10, 11, 12, 13, 14])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3*64.0], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64., 64., 64.],
        [64., 64., 64.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0][0:5]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[1][1]

6

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
t_d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(t_d)
print('\n',t_d[:3:,2])

[[0 1 2 3 4]
 [5 6 7 8 9]]

 [2 7]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
r_a=np.random.randint((10,10))
a=[10,8,9]
b=[5,4,3]
print('random numbers are ',r_a)
print(r_a.max())
print(r_a.min())

random numbers are  [6 6]
6
6


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a= np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.unique((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print('\n',data[names!="Will"])

[[ 0.44024659  0.03250894  0.51776111 -0.92532047]
 [ 1.05320806 -0.7978879  -2.09353252  1.23798583]
 [ 0.49236089 -1.20553222 -0.94734179 -0.80493981]
 [ 1.09481863  1.97743204 -0.86328706 -0.0263442 ]
 [ 1.81717999 -0.25728695  0.16580359 -1.93855659]
 [ 1.85552318 -0.23347834  0.26480764  1.30292835]
 [ 0.90630845  1.54167874 -1.73305938 -0.09841472]]

 [[ 0.44024659  0.03250894  0.51776111 -0.92532047]
 [ 1.05320806 -0.7978879  -2.09353252  1.23798583]
 [ 1.09481863  1.97743204 -0.86328706 -0.0263442 ]
 [ 1.85552318 -0.23347834  0.26480764  1.30292835]
 [ 0.90630845  1.54167874 -1.73305938 -0.09841472]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names=="Bob"]

array([[-1.08704877,  1.09547645, -0.52202981, -0.08475698],
       [ 0.51616993,  0.06855578, -0.60433571, -0.81463075]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
t_d=np.arange(1,16).reshape(5,3)
t_d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
t_d=np.arange(1,17,1).reshape(2,2,4)
t_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [33]:
t_d[0][1]=t_d[1][0]
t_d

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
s=np.random.randint(10)
print(s)
print(np.sqrt(s))
print(np.where(s<0.5,0,1))

0
0.0
0


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
ar1=np.array(np.random.rand(12))
ar2=np.array(np.random.rand(12))
print('\n',ar1)
print('\n',ar2)
print('\n',np.where(ar1>ar2,ar1,ar2))
print('\n',np.where(ar2>ar1,ar2,ar1))


 [0.8124353  0.86529176 0.40615455 0.87339156 0.46546402 0.68589292
 0.40301053 0.34737956 0.12120378 0.62221666 0.7496398  0.83098096]

 [0.44224073 0.23594479 0.39584854 0.00698565 0.04021977 0.46466615
 0.13222611 0.35665522 0.57851763 0.47720112 0.41540831 0.22321233]

 [0.8124353  0.86529176 0.40615455 0.87339156 0.46546402 0.68589292
 0.40301053 0.35665522 0.57851763 0.62221666 0.7496398  0.83098096]

 [0.8124353  0.86529176 0.40615455 0.87339156 0.46546402 0.68589292
 0.40301053 0.35665522 0.57851763 0.62221666 0.7496398  0.83098096]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a!=b)
print('\n',np.setdiff1d(a,b))

[ True  True  True  True  True]

 [1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print(sampleArray)
print('\n',sampleArray[:,:2])

[[34 43 73]
 [82 22 12]
 [53 94 66]]

 [[34 43]
 [82 22]
 [53 94]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
r=np.random.randn(20)
print(r)
print('\n',r.cumsum())

[ 0.93693278 -1.09037832 -0.05935583 -0.80790992  0.68098648  0.89791297
 -1.08363124  1.6662985   1.01749273  1.86368325  0.35953789  0.88695997
 -0.73710568  0.62419968  0.70402728  1.02757418 -1.13536972 -0.22444694
  0.21049801  1.01925974]

 [ 0.93693278 -0.15344554 -0.21280137 -1.02071129 -0.33972481  0.55818815
 -0.52544309  1.14085541  2.15834814  4.02203139  4.38156928  5.26852925
  4.53142357  5.15562325  5.85965053  6.88722471  5.75185499  5.52740805
  5.73790606  6.7571658 ]
